# Generated by Django 5.2.12 on 2026-04-05 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Masala'), ('GR', 'Ginger'), ('CD', 'Cardamom'), ('TL', 'Tulsi'), ('LM', 'Lemon'), ('SP', 'Spices'), ('PL', 'Plain')], max_length=2)),
            ],
        ),
    ]
